### ISSUE TITLE
ipcfabric/ is a copy of kineto's folder, consider using upstream

### ISSUE THREAD

**Issue by dzhulgakov** [facebookincubator/dynolog#57]
ipcfabric/ is the same between this repo and https://github.com/pytorch/kineto/tree/main/libkineto/ipcfabric . Consider adding a submodule dependency one way or another? Probably depending on libkineto from dynolog is preferred.

Additionally those files are licensed differently (BSD vs MIT)

**Comment by briancoutinho** [comment]
@dzhulgakov yes this is a known issue. The literal copy in Kineto was initially because we were still bootstrapping dynoloog on github. Another issue is Kineto is using C++14 so we had to use a slightly different version. 

Kineto is in the process of switching to C++ 17 and we will be removing that version of ipcfabric, and adding a submodule in kineto to get the ipcfabric code.
Let's keep this issue open and we can share updates as things progress.

**Comment by briancoutinho** [comment]
Marking this as resolved :) we have dynolog as dependency in kineto now.
https://github.com/pytorch/kineto/tree/main/libkineto/third_party
